apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: testset
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/Stemirabo/argo-examples.git
        revision: HEAD
        files:
          - path: "helm-webapp/values-*.yaml"
  template:
    metadata:
      name: 'innova-{{.path.filename}}'
    spec:
      project: test1
      source:
        repoURL: https://github.com/Stemirabo/argo-examples.git
        path: helm-webapp
        targetRevision: HEAD
        helm:
          valueFiles:
            - values.yaml
            - '{{.path.filename}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: test1
