apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: qa-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - git:
        repoURL: https://github.com/Stemirabo/argo-examples.git
        revision: HEAD
        files:
        - path: "sites/**/values.yaml"
      selector:
        matchExpressions:
          - key: argocd.enabled
            operator: In
            values:
              - "true"
          - key: argocd.environments.qa
            operator: In
            values:
              - "true"
          - key: app.bin
            operator: In
            values: ['0','1','2','3']
  template:
    metadata:
      name: '{{.path.basename}}-qa'
    spec:
      project: default
      source:
        repoURL: https://github.com/Stemirabo/argo-examples.git
        targetRevision: HEAD
        path: helm-webapp
        helm:
          valueFiles:
            - values.yaml
            - /zones/qa.values.yaml
            - '/{{.path.path}}/{{.path.filename}}'
          parameters: # overwrite values parameter for all sites
            - name: "replicas"
              value: "1"
      destination:
        server: https://kubernetes.default.svc
        namespace: 'ised-qa'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=false
