project: test1
source:
  repoURL: https://github.com/Stemirabo/argo-examples.git
  targetRevision: HEAD
  path: helm-webapp
  helm:
    valueFiles:
    - values.yaml
destination:
  server: 'https://kubernetes.default.svc'
  namespace: test1
