apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: git-directories-generator-ex1
  namespace: default
spec:
  generators:
  - list:
      elements:
      - xyz: dev
        path: v09-argocd-applicationSet-1/git-generator/resources/nginx-helm
      - xyz: prod
        path: v09-argocd-applicationSet-1/git-generator/resources/nginx-helm
  template:
    metadata:
      name: '{{xyz}}-application'
    spec:
      project: default
      source:
        repoURL: https://github.com/devopshobbies/argocd-tutorial.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
