apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/Stemirabo/argo-examples.git
              revision: HEAD
              files:
              - path: "sites/**/values.yaml"
            selector:
              matchExpressions:
                - key: argocd.enabled
                  operator: In
                  values:
                    - "true"
                - key: argocd.environments.dev
                  operator: In
                  values:
                    - "true"
                - key: app.bin
                  operator: In
                  values: ['0','1','2']
          - list:
              elements:
                - env: dev
                  namespace: ised-dev
                - env: qa
                  namespace: ised-qa
      selector:
        matchExpressions:
          - key: argocd.environment.{{.env}}
            operator: In
            values:
              - "true"
  template:
    metadata:
      name: '{{.path.basename}}-{{.env}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/Stemirabo/argo-examples.git
        targetRevision: HEAD
        path: helm-webapp
        helm:
          valueFiles:
            - values.yaml
            - /zones/{{.env}}.values.yaml
            - '/{{.path.path}}/{{.path.filename}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.namespace}}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
