apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - git:
        repoURL: https://github.com/Stemirabo/argo-examples.git
        revision: HEAD
        files:
        - path: "helm-webapp/values-*.yaml"
  template:
    metadata:
      name: 'innova-{{trimSuffix ".yaml" (trimPrefix "values-" .path.filename)}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/Stemirabo/argo-examples.git
        targetRevision: HEAD
        path: helm-webapp
        helm:
          valueFiles:
            - values.yaml
            - '{{.path.filename}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'default'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=false
