apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-appset
  namespace: default
spec:
  generators:
  - list:
      elements:
      - namespace: default
        xyz: dev
      - namespace: default
        xyz: prod
  template:
    metadata:
      name: '{{xyz}}-application'
    spec:
      project: default
      source:
        repoURL: https://github.com/Stemirabo/argo-examples.git
        targetRevision: HEAD
        path: helm-webapp
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
