apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-appset
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - potato: dev
      - potato: prod
  template:
    metadata:
      name: 'innova-{{.potato}}'
    spec:
      project: test1
      source:
        repoURL: https://github.com/Stemirabo/argo-examples.git
        targetRevision: HEAD
        path: helm-webapp
        helm:
          valueFiles:
          - values.yaml
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: test1
